### ISSUE TITLE
転生後の移動でクラッシュ

### ISSUE THREAD

**Issue by hinshiba** [dice-2004/Union-Hack-2024#30]
対応中です

以下エラー
Traceback (most recent call last):
  File "D:\dev\unionhack2024\Union-Hack-2024\src\main.py", line 379, in <module>
    main()
  File "D:\dev\unionhack2024\Union-Hack-2024\src\main.py", line 371, in main
    game.update()
  File "D:\dev\unionhack2024\Union-Hack-2024\src\main.py", line 174, in update
    self.next()
  File "D:\dev\unionhack2024\Union-Hack-2024\src\main.py", line 126, in next
    self.enemies.enemies[self.player.nowtile],
KeyError: 10

**Comment by hinshiba** [comment]
一度セーブandロードするとおこらなくなる

**Comment by dice-2004** [comment]
どこかで辞書型のデータが抜け落ちてるとかな気がする。
多分ですけど
